name: Full Sonar Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  scan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sonar scanner
        run: dotnet tool update --global dotnet-sonarscanner
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore Packages
        run: nuget restore NunitParallel.sln
      - name: Start sonarscanner
        run: dotnet sonarscanner begin /k:"oikz_SonarTesting_Full" /o:"oikz" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/*.trx"
      - name: Build solution
        run: msbuild NunitParallel.sln -t:rebuild -property:Configuration=Release
      - name: Test
        run: dotnet vstest NunitParallel/bin/Release/net481/NunitParallel.dll XUnitTests/bin/release/net481/XunitTests.dll XUnitTests2/bin/release/net481/XunitTests2.dll --parallel /Logger:"console;Verbosity=normal" /Logger:"trx;FileName=TestResults.trx"
      - name: End sonarscanner
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}